module.exports = {
  header: '// Autogenerated by Specford.\n',
  fn: `function(${args}) {\n${body}\n}`,
  expression: "function(${args}) {\nreturn ${body}\n}",
  autoEx: "(function(${args}) {\n${body}\n}(${passed}))"
};
