// Autogenerated by Specford.
var page, test = require('../src/utils/test'),
steps = [function(status) {
if(status !== 'success') console.log('Network error');
else {
test.start(new Date().getTime());
test.selectorHasText('body', 'About Google');
test.selectorDoesntHaveText('body', 'Foo bar baz');
test.stop(new Date().getTime());
test.report(2);
phantom.exit();
}
}],
next = function(url) {
if(page) page.close();
page = require('webpage').create();
page.open(url, steps.shift());
};
next('http://google.com');