// Autogenerated by Specford.
var page = require('webpage').create(), test = require('../src/utils/test');
page.open('http://google.com', function(status) {
if(status !== 'success') console.log('Network Error');
else {
test.start(new Date().getTime());
test.selectorHasText('body', 'About Google');
test.selectorDoesntHaveText('body', 'Foo bar baz');
test.stop(new Date().getTime());
test.report(2);
phantom.exit();

}
});
