// Autogenerated by Specford.
var Browser = require('zombie'),
browser = new Browser(),
test = require('../src/utils/test'),
callbacks = [function() {
browser.fire('click', 'section.home-search form', callbacks.shift());

},function() {
test.selectorExists('section#content-main div#search-results');
test.stop(new Date().getTime());
test.report(1);

}],
opened,
pages = [function() {
if(browser.statusCode !== 200) console.log('Network error');
else {
test.start(new Date().getTime());
console.log(browser.query('section.home-search'));
//browser.fill('section.home-search form input[name="q"]', 'input value', callbacks.shift());
}
}],
next = function(url) {
if(opened) browser.close();
browser.open({runScripts: false, loadCSS: false});
opened=true;
test.setBrowserRef(browser);
browser.visit(url, pages.shift());};
next('https://developer.mozilla.org/en-US/');