// Autogenerated by Specford.
var pg = null;
var Dom = require('../src/utils/dom');
var dom = new Dom;
var Tester = require('../src/utils/tester');
var test = new Tester(dom);
var colorizer = require('../src/utils/colorizer');
var Logger = require('../src/utils/logger');
var log = new Logger;
var steps = [
function(status) {
if(status !== 'success') log.unstamped('Network error', 'error');
else {
log.pgOpened();
test.start();
test.selectorExists('body', '.popup-container');
test.selectorExists('body', 'form.signup');
dom.clickSelector('body form.signup', 'button');
test.textExists('body form.signup', 'Your full name is required');
test.textExists('body form.signup', 'Your email is required');
test.textExists('body form.signup', 'Your password needs to be at least 8 characters');
dom.fillSelector('body form.signup', 'input[placeholder="First"]', 'Finn');
dom.clickSelector('body form.signup', 'button');
test.textDoesNotExist('body form.signup', 'Your full name is required');
test.textExists('body form.signup', 'Your last name is required');
test.stop();
slimer.exit();
}}
];
var visit = function(url) {
if(pg) pg.close();
else {
pg = require('webpage').create();
dom.setPageRef(pg);
pg.viewportSize = { width: 800, height: 600 };
pg.onConsoleMessage = function(msg) {log.unstamped(msg, 'magenta');};
pg.onNavigationRequested = function(url, type) {log.stamped(('navigating to: ' + url), 'gray');};
pg.onError = function(msg, tr) { var stack = ['ERROR: ' + msg]; if (tr && tr.length) { stack.push('TRACE:'); tr.forEach(function(t) { stack.push(' -> ' + t.file + ': ' + t.line + (t.function ? ' (in function *' + t.function +'*)' : '')); }); } log.unstamped(stack.join('\n'), 'yellow'); };
}
log.pgOpening();
pg.open(url, steps.shift());
};
visit('http://plangrid-test.herokuapp.com/en#signup');
