// Autogenerated by Specford.
var casper = require('casper').create();
casper.start('http://localhost:5001');
casper.then(function then() {
  this.test.assertSelectorExists('#container #header #logo');
  this.test.assertSelectorHasText('#container #header #header-nav', 'Log in');

});
casper.run(function run() {
  this.test.done(2);
  this.test.renderResults(true);

});
