// Autogenerated by Specford.
var page = require('webpage').create(), test = require('../src/utils/test');
page.open('http://xkcd.com/149', function(status) {
if(status !== 'success') console.log('Network Error');
else {
test.start(new Date().getTime());
test.selectorExists('#topContainer #masthead');
test.selectorHasText('#topContainer #masthead', 'A webcomic of');
test.selectorHasText('#topContainer #news', 'You can get');
test.selectorExists('#middleContainer #ctitle');
test.click('#middleContainer .comicNav a[rel="next"]');
page.onUrlChanged = function(targetUrl) {
test.stop(new Date().getTime());
test.report(4);
phantom.exit();

};
}
});
