// Autogenerated by Specford.
var casper = require('casper').create();
casper.start('http://xkcd.com/149');
casper.then(function then() {
  this.test.assertSelectorExists('#topContainer #masthead');
  this.test.assertSelectorHasText('#topContainer #masthead', 'A webcomic of');
  this.test.assertSelectorHasText('#topContainer #news', 'You can get');
  this.test.assertSelectorExists('#middleContainer #ctitle');
  this.click('#middleContainer .comicNav a[rel="next"]');

});
casper.then(function then() {
  this.test.assertUrlMatch(/xkcd.com\/150/);

});
casper.run(function run() {
  this.test.done(5);
  this.test.renderResults(true);

});
