module.exports = {
  TEXT: {
    exists: {
      after: "textExists",
      now: "test.textExists('${selector}', '${ref}');\n"
    },
    doesNotExist: {
      after: "textDoesNotExist",
      now: "test.textDoesNotExist('${selector}', '${ref}');\n"
    }
  },

  SELECTOR: {
    exists: {
      after: "selectorExists",
      now: "test.selectorExists('${selector}', '${ref}');\n"
    },
    doesNotExist: {
      after: "selectorDoesNotExist",
      now: "test.selectorDoesNotExist('${selector}', '${ref}');\n"
    },
    isVisible: {
      after: "selectorIsVisible",
      now: "test.selectorIsVisible('${selector}', '${ref}');\n"
    },
    isNotVisible: {
      after: "selectorIsNotVisible",
      now: "test.selectorIsNotVisible('${selector}', '${ref}');\n"
    },
    isSelected: {
      after: "selectorIsSelected",
      now: "test.selectorIsSelected('${selector}', '${ref}');\n"
    },
    isNotSelected: {
      after: "selectorIsNotSelected",
      now: "test.selectorIsNotSelected('${selector}', '${ref}');\n"
    }
  },

  NUMBER: {
    exist: {
      now: "test.countExists('${selector}', '${ref}', ${subject}, '${q}');\n",
      after: "test.countExists"
    },
    exists: {
      now: "test.countExists('${selector}', '${ref}', ${subject}, '${q}');\n",
      after: "test.countExists"
    }
  },

  URL: {
    contains: {
      after: "urlContains",
      now: "test.urlContains('${ref}');\n"
    },
    matches: {
      after: "urlMatches",
      now: "test.urlMatches('${ref}');\n"
    }
  },

  CLICK: "dom.clickSelector('${selector}', '${ref}');\n",

  SELECT: "dom.selectSelector('${selector}', '${ref}');\n",

  FILL: {
    REFERENCE: "dom.fillSelector('${selector}', '${ref}', '${val}');\n",
    IDENTIFIER: "dom.fillSelector('${selector}', '${ref}', ${val});\n"
  },

  // AFTER: "test.after.apply(test, ${args});\n" -- never more than 4 allowed
  AFTER: "test.after(steps.shift(), '${meth}', '${one}', '${two}', '${three}', '${four}');\n",

  CAPTURE: "pg.render('${name}.${ext}', {format: '${ext}', quality: '100'});\n",

  REQUIRE: "var ${fixture} = require('../../fixtures/${path}');\n",

  header: "// Autogenerated by Specford.\n",
  // a generic function wrapper for the rewriter
  genericWrapper: "function() {\n${body}}",
  openWrapper: "function(status) {\nif(status !== 'success') log.unstamped('Network error', 'error');\nelse {\n${body}}}",

  start: "test.start();\n",
  stop: "test.stop();\n",
  exit: "slimer.exit();\n",
  dom: "var Dom = require('../src/utils/dom');\nvar dom = new Dom;\n",
  tester: "var Tester = require('../src/utils/tester');\nvar test = new Tester(dom);\n",
  logger: "var Logger = require('../src/utils/logger');\nvar log = new Logger;\n",
  colorizer: "var colorizer = require('../src/utils/colorizer');\n",
  pgNull: "var pg = null;\n",
  pgIf: "if(pg) pg.close();\n",
  pgElse: {
    wrapper: "else {\n${body}}\n",
    create: "pg = require('webpage').create();\n",
    ref: "dom.setPageRef(pg);\n",
    viewport: "pg.viewportSize = { width: 800, height: 600 };\n",
    console: "pg.onConsoleMessage = function(msg) {log.unstamped(msg, 'magenta');};\n",
    nav: "pg.onNavigationRequested = function(url, type) {log.stamped(('navigating to: ' + url), 'gray');};\n",
    error: "pg.onError = function(msg, tr) { var stack = ['ERROR: ' + msg]; if (tr && tr.length) { stack.push('TRACE:'); tr.forEach(function(t) { stack.push(' -> ' + t.file + ': ' + t.line + (t.function ? ' (in function *' + t.function +'*)' : '')); }); } log.unstamped(stack.join('\\n'), 'yellow'); };\n"
  },
  pgOpen: "pg.open(url, steps.shift());\n",
  logOpening: "log.pgOpening();\n",
  logOpened: "log.pgOpened();\n",
  steps: "var steps = [\n${steps}\n];\n",
  visitFn: "var visit = function(url) {\n${body}};\n",
  visitCall: "visit('${url}');\n"
};
